"""
run_all.py — Master Execution Script

Runs the full analysis pipeline for:
"The Economics of Momentum: Evidence from Professional Esports"

Usage:
    python run_all.py              # Run all phases (skip parsing if cache exists)
    python run_all.py --from 3     # Start from Phase 3
    python run_all.py --only 7     # Run only Phase 7
    python run_all.py --parse      # Force re-parse demos (Phase 1)

Pipeline Phases:
    1. Demo Parsing        (01_pipeline.py)        — Requires demo files + awpy 1.2.3
    2. Exploratory         (02_exploratory.py)      — Stockholm only
    3. Decomposition       (03_decomposition.py)    — Stockholm: momentum decomposition
    4. Replication          (04_pattern_replication.py) — Antwerp confirmation
    5. Pooled Analysis     (05_pooled_analysis.py)  — Stockholm + Antwerp pooled
    6. Rio Validation      (06_testing_rio.py)      — Final holdout test
    7. Behavioral          (07_behavioral_analysis.py) — Force-buy rationality
    8. Clustered SEs       (08_clustered_errors.py) — Robustness: clustered errors
    9. HLTV Rankings       (09_hltv_rankings.py)    — Robustness: skill controls

Prerequisites:
    - Python 3.8+
    - pip install pandas numpy statsmodels matplotlib seaborn
    - For Phase 1 only: pip install awpy==1.2.3
    - Demo files in demos/ directory (Phase 1 only)
    - Cached CSVs in json_output/ (Phases 2-9, generated by Phase 1)

Authors: Vybhav Chaturvedi & Pranav Taneja
"""

import subprocess
import sys
import time
from pathlib import Path

# =============================================================================
# CONFIGURATION
# =============================================================================

BASE_DIR = Path(__file__).parent

PHASES = {
    1: {
        'script': '01_pipeline.py',
        'name': 'Demo Parsing',
        'description': 'Parse .dem files → round-level CSVs',
        'requires_demos': True,
    },
    2: {
        'script': '02_exploratory.py',
        'name': 'Exploratory Analysis',
        'description': 'Descriptive stats, visualizations, baseline momentum (Stockholm)',
    },
    3: {
        'script': '03_decomposition.py',
        'name': 'Momentum Decomposition',
        'description': 'Panel A (categorical) + Panel B (continuous) controls (Stockholm)',
    },
    4: {
        'script': '04_pattern_replication.py',
        'name': 'Pattern Replication',
        'description': 'Replicate Stockholm findings on Antwerp + diagnostics',
    },
    5: {
        'script': '05_pooled_analysis.py',
        'name': 'Pooled Analysis',
        'description': 'Combined Stockholm + Antwerp analysis',
    },
    6: {
        'script': '06_testing_rio.py',
        'name': 'Rio Validation',
        'description': 'Final holdout test on Rio 2022',
    },
    7: {
        'script': '07_behavioral_analysis.py',
        'name': 'Behavioral Analysis',
        'description': 'Force-buy rationality and expected value analysis',
    },
    8: {
        'script': '08_clustered_errors.py',
        'name': 'Clustered Standard Errors',
        'description': 'Robustness: cluster SEs by match_id',
    },
    9: {
        'script': '09_hltv_rankings.py',
        'name': 'HLTV Rankings',
        'description': 'Robustness: team skill controls via HLTV rankings',
    },
}


# =============================================================================
# RUNNER
# =============================================================================

def run_phase(phase_num: int, parse_flag: bool = False) -> bool:
    """
    Run a single phase script.

    Returns True if successful, False otherwise.
    """
    phase = PHASES[phase_num]
    script = BASE_DIR / phase['script']

    if not script.exists():
        print(f"  ERROR: Script not found: {script}")
        return False

    print(f"\n{'=' * 70}")
    print(f"PHASE {phase_num}: {phase['name'].upper()}")
    print(f"  {phase['description']}")
    print(f"  Script: {phase['script']}")
    print(f"{'=' * 70}\n")

    # Build command
    cmd = [sys.executable, str(script)]

    # Phase 1 special handling
    if phase_num == 1 and parse_flag:
        cmd.append('--parse')
    elif phase_num == 1 and not parse_flag:
        cmd.append('--load')  # default to loading cache

    # Run
    start_time = time.time()

    try:
        result = subprocess.run(
            cmd,
            cwd=str(BASE_DIR),
            capture_output=False,  # Show output in real time
            text=True,
        )

        elapsed = time.time() - start_time

        if result.returncode == 0:
            print(f"\n  Phase {phase_num} completed in {elapsed:.1f}s")
            return True
        else:
            print(f"\n  Phase {phase_num} FAILED (exit code {result.returncode})")
            return False

    except Exception as e:
        elapsed = time.time() - start_time
        print(f"\n  Phase {phase_num} ERROR after {elapsed:.1f}s: {e}")
        return False


def check_prerequisites():
    """Check that required data files exist."""
    json_dir = BASE_DIR / "json_output"

    required_csvs = [
        json_dir / "Stockholm" / "stockholm_rounds.csv",
        json_dir / "Antwerp" / "antwerp_rounds.csv",
        json_dir / "Rio" / "rio_rounds.csv",
    ]

    missing = [f for f in required_csvs if not f.exists()]

    if missing:
        print("\nWARNING: The following data files are missing:")
        for f in missing:
            print(f"  {f}")
        print("\nYou need to run Phase 1 (demo parsing) first,")
        print("or place pre-parsed CSVs in the json_output/ directory.")
        return False

    return True


# =============================================================================
# MAIN
# =============================================================================

def main():
    print("=" * 70)
    print("THE ECONOMICS OF MOMENTUM: FULL ANALYSIS PIPELINE")
    print("Vybhav Chaturvedi & Pranav Taneja")
    print("=" * 70)

    # Parse arguments
    args = sys.argv[1:]
    parse_flag = '--parse' in args
    start_from = 1
    only_phase = None

    for i, arg in enumerate(args):
        if arg == '--from' and i + 1 < len(args):
            start_from = int(args[i + 1])
        elif arg == '--only' and i + 1 < len(args):
            only_phase = int(args[i + 1])

    # Determine which phases to run
    if only_phase:
        phases_to_run = [only_phase]
    else:
        phases_to_run = [p for p in sorted(PHASES.keys()) if p >= start_from]

    # Skip Phase 1 unless explicitly requested or --parse flag
    if 1 in phases_to_run and not parse_flag and only_phase != 1:
        if check_prerequisites():
            print("\nCache found. Skipping Phase 1 (use --parse to force re-parsing).")
            phases_to_run = [p for p in phases_to_run if p != 1]
        else:
            print("\nNo cache found. Phase 1 will attempt to parse demos.")

    # Check prerequisites for phases 2+
    if any(p > 1 for p in phases_to_run):
        if not check_prerequisites():
            if 1 not in phases_to_run:
                print("\nCannot run Phases 2+ without data. Aborting.")
                sys.exit(1)

    # Print plan
    print(f"\nPhases to run: {phases_to_run}")
    print(f"Working directory: {BASE_DIR}")

    # Ensure output directory exists
    output_dir = BASE_DIR / "analysis_output"
    output_dir.mkdir(exist_ok=True)

    # Run phases
    total_start = time.time()
    results = {}

    for phase_num in phases_to_run:
        success = run_phase(phase_num, parse_flag=parse_flag)
        results[phase_num] = success

        if not success:
            print(f"\n{'!' * 70}")
            print(f"Phase {phase_num} failed. Stopping pipeline.")
            print(f"Fix the error above and re-run with: python run_all.py --from {phase_num}")
            print(f"{'!' * 70}")
            break

    # Summary
    total_elapsed = time.time() - total_start

    print(f"\n\n{'=' * 70}")
    print("PIPELINE SUMMARY")
    print(f"{'=' * 70}")
    print(f"\n{'Phase':<6} {'Name':<30} {'Status':<10}")
    print("-" * 50)

    for phase_num, success in results.items():
        name = PHASES[phase_num]['name']
        status = 'PASS' if success else 'FAIL'
        icon = '+' if success else 'X'
        print(f"  [{icon}]  {phase_num}. {name:<28} {status}")

    passed = sum(1 for s in results.values() if s)
    total = len(results)
    print(f"\n{passed}/{total} phases completed in {total_elapsed:.1f}s")

    if all(results.values()):
        print(f"\nAll outputs saved to: {output_dir}")
        print("\nKey output files:")
        print("  phase3_model_comparison.csv     — Momentum decomposition (Stockholm)")
        print("  phase4_replication_comparison.csv — Cross-tournament replication")
        print("  phase5_pooled_results.csv       — Pooled analysis results")
        print("  phase6_rio_validation.csv       — Rio holdout test")
        print("  phase7_behavioral_consolidated.csv — Force-buy EV analysis")
        print("  phase8_clustered_se_results.csv — Clustered SE robustness")
        print("  phase9_rank_controlled_results.csv — HLTV rank controls")
        print(f"\nFigures: fig_01 through fig_12 in {output_dir}")

    sys.exit(0 if all(results.values()) else 1)


if __name__ == "__main__":
    main()